name: Continuous Delivery

on:
  push:
    branches:
      - master

jobs:
  release:
    environment: production
    if: contains(github.event.commits[0].message, 'chore(release)') == false
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all history.
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16
      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          key: npm-${{ hashFiles('./package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline
      - name: Build
        run: npm run build
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: release
        name: Release
        uses: ridedott/release-me-action@master
        with:
          node-module: true
      - if: steps.release.outputs.released == 'true'
        name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.release.outputs.released == 'true'
        name: Publish to GitHub Packages
        run: npm publish
      - if: steps.release.outputs.released == 'true'
        name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          scope: '@merlinnot'
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: steps.release.outputs.released == 'true'
        name: Publish to npm
        run: npm publish --access public
    timeout-minutes: 10
